{% set name = "gobject-introspection" %}
{% set version = "1.63.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ '.'.join(version.split('.')[:2]) }}/{{ name }}-{{ version }}.tar.xz
  sha256: 476379bde8d080d92dd1bb1684f6aa8d79d90ddb81fc85dfa3576e36f9777ab6
  patches:
    - meson-rpaths.patch  # [linux]
    - gcc7-rpath-link.patch  # [linux]

build:
  number: 0
  skip: true  # [py<35]

requirements:
  build:
    - {{posix}}bison
    - {{posix}}flex
    - ninja
    - {{posix}}patch
    - {{native}}pkg-config
    - {{ compiler('c') }}
  host:
    - meson
    - cairo
    - gettext  # [osx]
    - glib
    - libffi
    - python
  run:
    - glib
    - libffi
    - python

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - g-ir-scanner --help  # [not win]
    - g-ir-compiler --help  # [not win]

about:
  home: https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
  license: LGPL-2.0-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'Middleware for binding GObject-based code to other languages.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - scopatz
